/* embedded_data.h - Embedded binary data accessors
 * Auto-generated by convert_binary_to_c.py
 */

#ifndef EMBEDDED_DATA_H
#define EMBEDDED_DATA_H

#include <stdint.h>
#include <stddef.h>

/* Look up Collision map (.collision) by relative path.
 * Returns pointer to static const data; DO NOT free().
 * Sets *out_size to data length. Returns NULL if not found. */
const uint8_t *embedded_collision_map(const char *path, size_t *out_size);

/* Look up Flipper radii/normal angle data by relative path.
 * Returns pointer to static const data; DO NOT free().
 * Sets *out_size to data length. Returns NULL if not found. */
const uint8_t *embedded_flipper_data(const char *path, size_t *out_size);

/* Look up Tilt force table by relative path.
 * Returns pointer to static const data; DO NOT free().
 * Sets *out_size to data length. Returns NULL if not found. */
const uint8_t *embedded_tilt_table(const char *path, size_t *out_size);

/* Look up Ball physics force field by relative path.
 * Returns pointer to static const data; DO NOT free().
 * Sets *out_size to data length. Returns NULL if not found. */
const uint8_t *embedded_physics_data(const char *path, size_t *out_size);

/* Look up Collision angle table by relative path.
 * Returns pointer to static const data; DO NOT free().
 * Sets *out_size to data length. Returns NULL if not found. */
const uint8_t *embedded_collision_angles(const char *path, size_t *out_size);

/* Look up Tilemap (.map) by relative path.
 * Returns pointer to static const data; DO NOT free().
 * Sets *out_size to data length. Returns NULL if not found. */
const uint8_t *embedded_tilemap(const char *path, size_t *out_size);

/* Look up Background attributes (.bgattr) by relative path.
 * Returns pointer to static const data; DO NOT free().
 * Sets *out_size to data length. Returns NULL if not found. */
const uint8_t *embedded_bgattr(const char *path, size_t *out_size);

/* Try external file first, fall back to embedded data.
 * ALWAYS returns a malloc'd copy (caller must free).
 * Returns NULL only if both sources unavailable. */
uint8_t *load_binary_data(const char *base_path,
                          const char *relative_path,
                          size_t *out_size);

#endif /* EMBEDDED_DATA_H */
